site_name: Acuparse Documentation
site_url: https://docs.acuparse.com/
repo_url: https://github.com/acuparse/acuparse/
repo_name: acuparse/acuparse
edit_uri: ""
theme:
  name: material
  features:
    - navigation.instant
  palette:
    scheme: preference
    primary: black
  icon:
    repo: fontawesome/brands/github
site_dir: public
nav:
  - Home: 'index.md'
  - Installing:
      - Main Install Guide: 'INSTALL.md'
      - Docker Install Guide: 'DOCKER.md'
      - Realtime Install Guide: 'REALTIME.md'
      - Supplemental Guides:
          - DNS Redirect: 'other/DNS.md'
          - NGINX Proxy: 'other/NGINX.md'
          - RaspberryPi Direct Connect: 'other/RPI_DIRECT_CONNECT.md'
          - Backups: 'other/BACKUPS.md'
          - Telemetry: 'other/TELEMETRY.md'
  - Updating:
      - Update Guide: 'UPDATING.md'
      - Version 3.0: 'updates/v3.md'
      - Version 2.3: 'updates/v2_3.md'
  - API Guide: 'API.md'
  - Troubleshooting Guide: 'TROUBLESHOOTING.md'
  - External Updaters:
      - Weather Underground: 'external/WU.md'
      - CWOP: 'external/CWOP.md'
      - PWS Weather: 'external/PWS.md'
      - Weathercloud: 'external/WC.md'
      - Windy: 'external/WINDY.md'
      - Windguru: 'external/WINDGURU.md'
      - Open Weather Map: 'external/OPENWEATHER.md'
      - MQTT: 'external/MQTT.md'
      - Generic:
          - WeatherPoly: 'external/generic/WEATHERPOLY.md'
copyright: "Copyright © 2015-2023 <a href='https://www.acuparse.com'>Acuparse Project</a><br />Acuparse is licensed under the <a href='https://gitlab.com/acuparse/acuparse/-/raw/stable/LICENSE'>GNU AGPLv3</a>"
extra:
  social:
    - type: 'slack'
      link: 'https://communityinviter.com/apps/acuparse/docs'
      icon: 'fontawesome/brands/slack'
    - type: 'gitlab'
      link: 'https://gitlab.com/acuparse'
      icon: 'fontawesome/brands/gitlab'
    - type: 'github'
      link: 'https://github.com/acuparse'
      icon: 'fontawesome/brands/github'
    - type: 'bitbucket'
      link: 'https://bitbucket.com/acuparse'
      icon: 'fontawesome/brands/bitbucket'
    - type: 'facebook'
      link: 'https://facebook.com/acuparse'
      icon: 'fontawesome/brands/facebook'
  manifest: 'manifest.webmanifest'
  search:
    language: 'en'
  analytics:
    provider: google
    property: G-FZHKZ4WJZS
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
